export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '@/app/(pages)/globals.css'
import { Navbar } from '@/components/navbar'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {' '}
      <Navbar />
      {children}
    </>
  )
}
